name: 🚀 Build Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      runnerMain:
        type: string
        required: true
        default: 'ubuntu-latest'
      runnerMacos:
        type: string
        required: true
        default: 'macos-latest'
      buildTargets:
        type: string
        required: true
        default: '["StandaloneWindows64", "StandaloneLinux64"]'
      metadataConfig:
        type: string
        required: true
        default: '{"projectName":"game","buildVersion":"1.0.0","retentionDays":"7","timeoutMinutesBuild":"60","unityVersion":"2022.3.0f1"}'
      artifactConfig:
        type: string
        required: true
        default: '{"requiresCombined":"false"}'

permissions:
  contents: write

jobs:
  unpack_inputs:
    name: Unpack Inputs
    runs-on: ${{ inputs.runnerMain || 'ubuntu-latest' }}
    outputs:
      projectName: ${{ steps.unpack.outputs.projectName }}
      buildVersion: ${{ steps.unpack.outputs.buildVersion }}
      retentionDays: ${{ steps.unpack.outputs.retentionDays }}
      requiresCombined: ${{ steps.unpack.outputs.requiresCombined }}
      unityVersion: ${{ steps.unpack.outputs.unityVersion }}
      timeoutMinutesBuild: ${{ steps.unpack.outputs.timeoutMinutesBuild }}
      runnerMain: ${{ steps.unpack.outputs.runnerMain }}
      runnerMacos: ${{ steps.unpack.outputs.runnerMacos }}
      buildTargets: ${{ steps.unpack.outputs.buildTargets }}
    steps:
      - id: unpack
        run: |
          # Set defaults for push/PR events
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            meta='${{ inputs.metadataConfig }}'
            artifact='${{ inputs.artifactConfig }}'
            runnerMain='${{ inputs.runnerMain }}'
            runnerMacos='${{ inputs.runnerMacos }}'
            buildTargets='${{ inputs.buildTargets }}'
          else
            # Default values for push/PR
            meta='{"projectName":"game","buildVersion":"1.0.0","retentionDays":"7","timeoutMinutesBuild":"60","unityVersion":"2022.3.0f1"}'
            artifact='{"requiresCombined":"false"}'
            runnerMain='ubuntu-latest'
            runnerMacos='macos-latest'
            buildTargets='["StandaloneWindows64", "StandaloneLinux64"]'
          fi

          # Metadata Config
          echo "projectName=$(echo "$meta" | jq -r .projectName)" >> "$GITHUB_OUTPUT"
          echo "buildVersion=$(echo "$meta" | jq -r .buildVersion)" >> "$GITHUB_OUTPUT"
          echo "retentionDays=$(echo "$meta" | jq -r .retentionDays)" >> "$GITHUB_OUTPUT"
          echo "timeoutMinutesBuild=$(echo "$meta" | jq -r .timeoutMinutesBuild)" >> "$GITHUB_OUTPUT"
          echo "unityVersion=$(echo "$meta" | jq -r .unityVersion)" >> "$GITHUB_OUTPUT"

          # Artifacts Config
          echo "requiresCombined=$(echo "$artifact" | jq -r .requiresCombined)" >> "$GITHUB_OUTPUT"
          
          # Runner Config
          echo "runnerMain=$runnerMain" >> "$GITHUB_OUTPUT"
          echo "runnerMacos=$runnerMacos" >> "$GITHUB_OUTPUT"
          echo "buildTargets=$buildTargets" >> "$GITHUB_OUTPUT"

  # ─────────────────────────────────────────────────────────────────────────────
  # Build and Create Zipped Artifacts
  # ─────────────────────────────────────────────────────────────────────────────
  build:
    name: Build
    needs: unpack_inputs
    uses: avalin/unity-ci-templates/.github/workflows/step-2-build.yml@v1
    with:
      runnerMain: ${{ needs.unpack_inputs.outputs.runnerMain }}
      runnerMacos: ${{ needs.unpack_inputs.outputs.runnerMacos }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      unityVersion: ${{ needs.unpack_inputs.outputs.unityVersion }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      buildType: 'development'
      buildTargets: ${{ needs.unpack_inputs.outputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      timeoutMinutes: ${{ fromJson(needs.unpack_inputs.outputs.timeoutMinutesBuild) }}
      retentionDays: ${{ fromJson(needs.unpack_inputs.outputs.retentionDays) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
