name: Build (Windows + Linux)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.targetPlatform }}
    environment: main
    runs-on: [self-hosted, windows]        # your local Windows runner
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64            # Windows x86_64
          - StandaloneLinux64              # Linux x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true                        # supports large assets if you use LFS

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-

      - name: Detect Docker OSType
        id: detect-docker
        shell: bash
        run: |
          # Query the Docker daemon for its OSType (linux or windows). If docker isn't
          # available or the query fails, set 'unknown'. This is used to avoid passing
          # Windows-only isolation options to a Linux daemon.
          dockerOs=$(docker info --format '{{.OSType}}' 2>/dev/null || echo 'unknown')
          echo "Detected Docker OSType: $dockerOs"
          echo "docker_os=$dockerOs" >> $GITHUB_OUTPUT

      - name: Build with GameCI
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}   # base64 .ulf license file
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform:      ${{ matrix.targetPlatform }}
          # Use POSIX-style path for dockerWorkspacePath on Windows self-hosted runners.
          # This prevents duplicate drive-letter prefixes like "c:C:\github\workspace"
          # which cause Docker "too many colons" mount errors.
          dockerWorkspacePath: '/github/workspace'
          # Use 'process' isolation only when the target is Windows AND the Docker daemon
          # itself reports a Windows OSType. Otherwise fall back to 'default'.
          dockerIsolationMode: ${{ (matrix.targetPlatform == 'StandaloneWindows64' && steps.detect-docker.outputs.docker_os == 'windows') && 'process' || 'default' }}
          runAsHostUser:       true

      - name: Compress build output (zip)
        shell: pwsh
        run: |
          $target = "${{ matrix.targetPlatform }}"
          Compress-Archive -Path "build\$target" -DestinationPath "build\$target.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}.zip
