name: 🚀 Build Pipeline

on:
  workflow_dispatch:
    inputs:
      runnerMain:
        type: string
        required: true
      runnerMacos:
        type: string
        required: true
      buildTargets:
        type: string
        required: true
        default: '[]'
      metadataConfig:
        type: string
        required: true
      artifactConfig:
        type: string
        required: true

permissions:
  contents: write

jobs:
  unpack_inputs:
    name: Unpack Inputs
    runs-on: ${{ inputs.runnerMain }}
    outputs:
      projectName: ${{ steps.unpack.outputs.projectName }}
      buildVersion: ${{ steps.unpack.outputs.buildVersion }}
      retentionDays: ${{ steps.unpack.outputs.retentionDays }}
      requiresCombined: ${{ steps.unpack.outputs.requiresCombined }}
      unityVersion: ${{ steps.unpack.outputs.unityVersion }}
      timeoutMinutesBuild: ${{ steps.unpack.outputs.timeoutMinutesBuild }}
    steps:
      - id: unpack
        run: |
          meta='${{ inputs.metadataConfig }}'
          artifact='${{ inputs.artifactConfig }}'

          # Metadata Config
          echo "projectName=$(echo "$meta" | jq -r .projectName)" >> "$GITHUB_OUTPUT"
          echo "buildVersion=$(echo "$meta" | jq -r .buildVersion)" >> "$GITHUB_OUTPUT"
          echo "retentionDays=$(echo "$meta" | jq -r .retentionDays)" >> "$GITHUB_OUTPUT"
          echo "timeoutMinutesBuild=$(echo "$meta" | jq -r .timeoutMinutesBuild)" >> "$GITHUB_OUTPUT"
          echo "unityVersion=$(echo "$meta" | jq -r .unityVersion)" >> "$GITHUB_OUTPUT"

          # Artifacts Config
          echo "requiresCombined=$(echo "$artifact" | jq -r .requiresCombined)" >> "$GITHUB_OUTPUT"

  # ─────────────────────────────────────────────────────────────────────────────
  # Build and Create Zipped Artifacts
  # ─────────────────────────────────────────────────────────────────────────────
  build:
    name: Build
    needs: unpack_inputs
    uses: avalin/unity-ci-templates/.github/workflows/step-2-build.yml@v1
    with:
      runnerMain: ${{ inputs.runnerMain }}
      runnerMacos: ${{ inputs.runnerMacos }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      unityVersion: ${{ needs.unpack_inputs.outputs.unityVersion }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      buildType: 'development'
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      timeoutMinutes: ${{ fromJson(needs.unpack_inputs.outputs.timeoutMinutesBuild) }}
      retentionDays: ${{ fromJson(needs.unpack_inputs.outputs.retentionDays) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
