name: 🚀 CD Pipeline (Build, Release & Deploy)

on:
  workflow_dispatch:
    inputs:
      runnerMain:
        type: string
        required: true
      runnerMacos:
        type: string
        required: true
      validDeployTargets:
        type: string
        required: true
        default: '[]'
      buildTargets:
        type: string
        required: true
        default: '[]'
      metadataConfig:
        type: string
        required: true
      artifactConfig:
        type: string
        required: true

permissions:
  contents: write

jobs:
  unpack_inputs:
    name: Unpack Inputs
    runs-on: ${{ inputs.runnerMain }}
    outputs:
      projectName: ${{ steps.unpack.outputs.projectName }}
      buildType: ${{ steps.unpack.outputs.buildType }}
      buildVersion: ${{ steps.unpack.outputs.buildVersion }}
      retentionDays: ${{ steps.unpack.outputs.retentionDays }}
      requiresCombined: ${{ steps.unpack.outputs.requiresCombined }}
      skipPerBuildTarget: ${{ steps.unpack.outputs.skipPerBuildTarget }}
      unityVersion: ${{ steps.unpack.outputs.unityVersion }}
      timeoutMinutesBuild: ${{ steps.unpack.outputs.timeoutMinutesBuild }}
    steps:
      - id: unpack
        run: |
          meta='${{ inputs.metadataConfig }}'
          artifact='${{ inputs.artifactConfig }}'

          # Metadata Config
          echo "projectName=$(echo "$meta" | jq -r .projectName)" >> "$GITHUB_OUTPUT"
          echo "buildType=$(echo "$meta" | jq -r .buildType)" >> "$GITHUB_OUTPUT"
          echo "buildVersion=$(echo "$meta" | jq -r .buildVersion)" >> "$GITHUB_OUTPUT"
          echo "retentionDays=$(echo "$meta" | jq -r .retentionDays)" >> "$GITHUB_OUTPUT"
          echo "timeoutMinutesBuild=$(echo "$meta" | jq -r .timeoutMinutesBuild)" >> "$GITHUB_OUTPUT"
          echo "unityVersion=$(echo "$meta" | jq -r .unityVersion)" >> "$GITHUB_OUTPUT"

          # Artifacts Config
          echo "requiresCombined=$(echo "$artifact" | jq -r .requiresCombined)" >> "$GITHUB_OUTPUT"
          echo "skipPerBuildTarget=$(echo "$artifact" | jq -r .skipPerBuildTarget)" >> "$GITHUB_OUTPUT"

  # ─────────────────────────────────────────────────────────────────────────────
  # 1. Build
  # ─────────────────────────────────────────────────────────────────────────────
  build:
    name: Build
    needs: unpack_inputs
    uses: avalin/unity-ci-templates/.github/workflows/step-2-build.yml@v1
    with:
      # If the event is a push with a tag, force buildType to "release"; otherwise, use the input.
      runnerMain: ${{ inputs.runnerMain }}
      runnerMacos: ${{ inputs.runnerMacos }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      unityVersion: ${{ needs.unpack_inputs.outputs.unityVersion }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      timeoutMinutes: ${{ fromJson(needs.unpack_inputs.outputs.timeoutMinutesBuild) }}
      retentionDays: ${{ fromJson(needs.unpack_inputs.outputs.retentionDays) }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 2. Release
  # ─────────────────────────────────────────────────────────────────────────────
  release:
    name: Release
    needs: 
      - unpack_inputs
      - build
    if: > 
      always() &&
      needs.build.result == 'success' && 
      (
        needs.unpack_inputs.outputs.buildType == 'release' || 
        needs.unpack_inputs.outputs.buildType == 'release_candidate'
      )
    uses: avalin/unity-ci-templates/.github/workflows/step-3-release.yml@v1
    with:
      runnerMain: ${{ inputs.runnerMain }}
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      skipPerBuildTargetArtifacts: ${{ needs.unpack_inputs.outputs.skipPerBuildTarget }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 3. Deploy
  # ─────────────────────────────────────────────────────────────────────────────
  deploy:
    name: Deploy
    needs: 
      - unpack_inputs
      - build
      - release
    if: > 
      always() &&
       needs.release.result == 'success' &&
       inputs.validDeployTargets != '[]'
    uses: avalin/unity-ci-templates/.github/workflows/step-4-deploy.yml@v1
    with:
      runnerMain: ${{ inputs.runnerMain }}
      runnerMacos: ${{ inputs.runnerMacos }}
      buildType: ${{ needs.unpack_inputs.outputs.buildType }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      projectName: ${{ needs.unpack_inputs.outputs.projectName }}
      deployTargets: ${{ inputs.validDeployTargets }}
      buildTargets: ${{ inputs.buildTargets }}
      hasCombinedArtifacts: ${{ needs.unpack_inputs.outputs.requiresCombined }}
      artifactSource: build
    secrets:
      CICD_PAT: ${{ secrets.CICD_PAT }}
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      DEPLOY_API_KEY: ${{ secrets.DEPLOY_API_KEY }}
      ITCH_USERNAME: ${{ secrets.ITCH_USERNAME }}
      ITCH_PROJECT: ${{ secrets.ITCH_PROJECT }}
      APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
      STEAM_DEPOT_VDF_PATH: ${{ secrets.STEAM_DEPOT_VDF_PATH }}
      APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
      APPSTORE_API_ISSUER_ID: ${{ secrets.APPSTORE_API_ISSUER_ID }}
      APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      CUSTOM_SERVER_HOST: ${{ secrets.CUSTOM_SERVER_HOST }}
      CUSTOM_SERVER_USER: ${{ secrets.CUSTOM_SERVER_USER }}
      CUSTOM_SERVER_KEY: ${{ secrets.CUSTOM_SERVER_KEY }}

  # ─────────────────────────────────────────────────────────────────────────────
  # 4. Notify
  # ─────────────────────────────────────────────────────────────────────────────
  notify:
    name: Notify
    needs: 
      - unpack_inputs
      - build
      - release
      - deploy
    if: > 
      always() && 
      (
        needs.unpack_inputs.outputs.buildType == 'release' || 
        needs.unpack_inputs.outputs.buildType == 'release_candidate'
      )
    uses: avalin/unity-ci-templates/.github/workflows/step-5-notify.yml@v1
    with:
      runnerMain: ${{ inputs.runnerMain }}
      buildVersion: ${{ needs.unpack_inputs.outputs.buildVersion }}
      releaseResult: ${{ needs.release.result }}
      releaseErrorMessage: ${{ needs.release.outputs.releaseErrorMessage }}
      deployResult: ${{ needs.deploy.result }}
      testsHasFails: 'false'
      testsTotal: '0'
      testsPassed: '0'
      testsFailedNames: '[]'
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
